name: Brew install

on: [push]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: read

    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{matrix.os}}

    steps:
    - name: Install
      run: |
        brew update
        brew tap bbc/audiowaveform
        brew install --verbose audiowaveform
        audiowaveform --version
