name: Brew install

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{matrix.os}}

    steps:
    - name: Install
      run: |
        brew update
        brew tap bbc/audiowaveform
        brew install audiowaveform
        audiowaveform --version
